language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
install: pip install -r requires.txt -r requires-test.txt --use-mirrors
# command to run tests
script:  python -m unittest tests